<?php
namespace App\Services;

use Illuminate\Support\Facades\DB;
use Illuminate\Support\Str;

final class LearningGovernanceScaleService
{
 public function recordOutcome(array $input): string {
  $id=Str::uuid()->toString(); $now=now();
  DB::table('lh_learning_events')->insert(['id'=>$id,'event_type'=>$input['event_type']??'outcome','subject_type'=>$input['subject_type']??null,'subject_id'=>$input['subject_id']??null,'opportunity_id'=>$input['opportunity_id']??null,'label'=>$input['label']??null,'label_value'=>$input['label_value']??null,'features'=>json_encode($input['features']??[]),'context'=>json_encode($input['context']??[]),'source'=>$input['source']??'system','actor'=>$input['actor']??'system','occurred_at'=>$input['occurred_at']??$now,'created_at'=>$now,'updated_at'=>$now]);
  return $id;
 }
 public function snapshotFeatures(array $input): string {
  $features=$input['features']??[]; ksort($features); $json=json_encode($features,JSON_UNESCAPED_UNICODE|JSON_UNESCAPED_SLASHES); $id=Str::uuid()->toString();
  DB::table('lh_feature_snapshots')->insert(['id'=>$id,'feature_set'=>$input['feature_set']??'default','entity_type'=>$input['entity_type']??null,'entity_id'=>$input['entity_id']??null,'opportunity_id'=>$input['opportunity_id']??null,'schema_version'=>$input['schema_version']??'1.0','features'=>$json,'feature_hash'=>hash('sha256',$json),'as_of'=>$input['as_of']??now(),'created_at'=>now()]); return $id;
 }
 public function registerModel(array $input): string { $id=Str::uuid()->toString(); DB::table('lh_model_versions')->insert(['id'=>$id,'model_key'=>$input['model_key'],'version'=>$input['version'],'model_type'=>$input['model_type']??'rules','status'=>'candidate','training_data_version'=>$input['training_data_version']??null,'hyperparameters'=>json_encode($input['hyperparameters']??[]),'metrics'=>json_encode($input['metrics']??[]),'approval'=>json_encode([]),'artifact_uri'=>$input['artifact_uri']??null,'trained_at'=>$input['trained_at']??now(),'created_at'=>now(),'updated_at'=>now()]); return $id; }
 public function promoteModel(string $id,string $actor,array $approval=[]): void { $m=DB::table('lh_model_versions')->where('id',$id)->first(); if(!$m) throw new \RuntimeException('Model not found'); DB::transaction(function() use($m,$id,$actor,$approval){DB::table('lh_model_versions')->where('model_key',$m->model_key)->where('status','production')->update(['status'=>'retired','retired_at'=>now(),'updated_at'=>now()]); DB::table('lh_model_versions')->where('id',$id)->update(['status'=>'production','promoted_at'=>now(),'approval'=>json_encode(['actor'=>$actor,'approved_at'=>now()->toIso8601String(),'details'=>$approval]),'updated_at'=>now()]); $this->audit('model_promoted','system',$actor,'lh_model_versions',$id,'model_promotion',null,['status'=>'production']);}); }
 public function recordPrediction(array $input): string { $id=Str::uuid()->toString(); DB::table('lh_predictions')->insert(['id'=>$id,'model_version_id'=>$input['model_version_id'],'prediction_type'=>$input['prediction_type'],'subject_type'=>$input['subject_type'],'subject_id'=>$input['subject_id'],'opportunity_id'=>$input['opportunity_id']??null,'score'=>$input['score']??null,'probability'=>$input['probability']??null,'explanation'=>json_encode($input['explanation']??[]),'features'=>json_encode($input['features']??[]),'decision'=>$input['decision']??null,'predicted_at'=>$input['predicted_at']??now(),'created_at'=>now(),'updated_at'=>now()]); return $id; }
 public function attachPredictionOutcome(string $predictionId,string $label,?float $value=null): void {DB::table('lh_predictions')->where('id',$predictionId)->update(['outcome_label'=>$label,'outcome_value'=>$value,'outcome_at'=>now(),'updated_at'=>now()]);}
 public function createDriftAlert(array $input): string { $id=Str::uuid()->toString(); DB::table('lh_drift_alerts')->insert(['id'=>$id,'drift_type'=>$input['drift_type'],'feature_key'=>$input['feature_key']??null,'model_key'=>$input['model_key']??null,'baseline_value'=>$input['baseline_value']??null,'current_value'=>$input['current_value']??null,'drift_score'=>$input['drift_score']??null,'severity'=>$input['severity']??'medium','status'=>'open','evidence'=>json_encode($input['evidence']??[]),'detected_at'=>now(),'created_at'=>now(),'updated_at'=>now()]); return $id; }
 public function sourceScorecard(string $source, string $from,string $to): array { $q=DB::table('lh_learning_events')->whereBetween('occurred_at',[$from,$to]); $ing=(clone $q)->where('source',$source)->count(); $won=(clone $q)->where('source',$source)->where('label','won')->count(); $qual=(clone $q)->where('source',$source)->where('label','qualified')->count(); $verified=(clone $q)->where('source',$source)->where('label','verified')->count(); $dupes=(clone $q)->where('source',$source)->where('label','duplicate')->count(); $risk=(clone $q)->where('source',$source)->where('label','risk')->count(); $conv=$ing?round($won/$ing,4):0; $quality=$ing?round((($verified/$ing)*50+(max(0,$ing-$dupes)/max(1,$ing))*25+(max(0,$ing-$risk)/max(1,$ing))*25),2):0; return compact('source','from','to','ing','won','qual','verified','dupes','risk','conv','quality'); }
 public function qualityCheck(array $scope=[]): array { $issues=[]; $checks=0; $pass=0; foreach([['predictions_missing_model',DB::table('lh_predictions')->whereNotExists(function($q){$q->select(DB::raw(1))->from('lh_model_versions')->whereColumn('lh_model_versions.id','lh_predictions.model_version_id');})->count()],['events_missing_time',DB::table('lh_learning_events')->whereNull('occurred_at')->count()],['features_missing_hash',DB::table('lh_feature_snapshots')->whereNull('feature_hash')->count()]] as [$name,$bad]){$checks++;if($bad===0)$pass++;else $issues[$name]=$bad;} return ['checks'=>$checks,'passed'=>$pass,'quality_score'=>$checks?round($pass/$checks*100,2):0,'issues'=>$issues]; }
 public function governanceDecision(string $policyKey,array $context): array { $p=DB::table('lh_governance_policies')->where('policy_key',$policyKey)->where('status','active')->first(); if(!$p) return ['decision'=>'review','reason'=>'No active policy']; $rules=json_decode($p->rules,true)?:[]; foreach(($rules['deny_if']??[]) as $key=>$value){if(($context[$key]??null)===$value){return ['decision'=>'deny','reason'=>'Policy rule matched','rule'=>$key];}} foreach(($rules['review_if']??[]) as $key=>$value){if(($context[$key]??null)===$value){return ['decision'=>'review','reason'=>'Policy rule matched','rule'=>$key];}} return ['decision'=>$rules['default']??'allow','reason'=>'Default policy decision']; }
 public function audit(string $event,string $actorType,string $actor,string $subjectType,?string $subjectId,string $policy=null,?array $before=null,?array $after=null): string { $id=Str::uuid()->toString(); DB::table('lh_governance_audits')->insert(['id'=>$id,'event_type'=>$event,'actor_type'=>$actorType,'actor_id'=>$actor,'subject_type'=>$subjectType,'subject_id'=>$subjectId,'policy_key'=>$policy,'request_id'=>request()?->header('X-Request-ID'),'correlation_id'=>request()?->header('X-Correlation-ID'),'before_state'=>json_encode($before),'after_state'=>json_encode($after),'reason'=>json_encode([]),'ip_hash'=>request()?->ip()?hash('sha256',request()->ip()):null,'occurred_at'=>now(),'created_at'=>now(),'updated_at'=>now()]); return $id; }
 public function assignExperiment(string $experimentKey,string $subjectType,string $subjectId): string { $e=DB::table('lh_experiments')->where('experiment_key',$experimentKey)->where('status','running')->first(); if(!$e) throw new \RuntimeException('Experiment not running'); $hash=hash('sha256',$experimentKey.'|'.$subjectType.'|'.$subjectId); $existing=DB::table('lh_experiment_assignments')->where('assignment_hash',$hash)->first(); if($existing)return $existing->id; $variants=json_decode($e->variants,true)?:['control'=>50]; $bucket=hexdec(substr($hash,0,8))%10000/100; $cursor=0;$chosen=array_key_first($variants); foreach($variants as $v=>$pct){$cursor+=(float)$pct;if($bucket<$cursor){$chosen=$v;break;}} $id=Str::uuid()->toString(); DB::table('lh_experiment_assignments')->insert(['id'=>$id,'experiment_id'=>$e->id,'subject_type'=>$subjectType,'subject_id'=>$subjectId,'variant'=>$chosen,'assignment_hash'=>$hash,'assigned_at'=>now(),'created_at'=>now(),'updated_at'=>now()]); return $id; }
}
