<?php
use Illuminate\Database\Migrations\Migration;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Support\Facades\Schema;

return new class extends Migration {
 public function up(): void {
  Schema::create('lh_learning_events', function(Blueprint $t){$t->uuid('id')->primary();$t->string('event_type',80)->index();$t->string('subject_type',80)->nullable();$t->uuid('subject_id')->nullable()->index();$t->uuid('opportunity_id')->nullable()->index();$t->string('label',80)->nullable();$t->decimal('label_value',12,4)->nullable();$t->json('features')->nullable();$t->json('context')->nullable();$t->string('source',80)->nullable();$t->string('actor')->nullable();$t->timestamp('occurred_at')->index();$t->timestamp('created_at')->nullable();$t->timestamp('updated_at')->nullable();});
  Schema::create('lh_feature_snapshots', function(Blueprint $t){$t->uuid('id')->primary();$t->string('feature_set',120)->index();$t->string('entity_type',80)->nullable();$t->uuid('entity_id')->nullable()->index();$t->uuid('opportunity_id')->nullable()->index();$t->string('schema_version',40);$t->json('features');$t->string('feature_hash',64)->index();$t->timestamp('as_of')->index();$t->timestamp('created_at')->nullable();});
  Schema::create('lh_model_versions', function(Blueprint $t){$t->uuid('id')->primary();$t->string('model_key',120)->index();$t->string('version',60);$t->string('model_type',60);$t->string('status',30)->default('candidate')->index();$t->string('training_data_version')->nullable();$t->json('hyperparameters')->nullable();$t->json('metrics')->nullable();$t->json('approval')->nullable();$t->string('artifact_uri')->nullable();$t->timestamp('trained_at')->nullable();$t->timestamp('promoted_at')->nullable();$t->timestamp('retired_at')->nullable();$t->created_at();$t->updated_at();$t->unique(['model_key','version']);});
  Schema::create('lh_predictions', function(Blueprint $t){$t->uuid('id')->primary();$t->uuid('model_version_id')->index();$t->string('prediction_type',100)->index();$t->string('subject_type',80);$t->uuid('subject_id')->index();$t->uuid('opportunity_id')->nullable()->index();$t->decimal('score',12,6)->nullable();$t->decimal('probability',12,8)->nullable();$t->json('explanation')->nullable();$t->json('features')->nullable();$t->string('decision',60)->nullable();$t->timestamp('predicted_at')->index();$t->timestamp('outcome_at')->nullable();$t->string('outcome_label',80)->nullable();$t->decimal('outcome_value',12,4)->nullable();$t->timestamps();});
  Schema::create('lh_calibration_runs', function(Blueprint $t){$t->uuid('id')->primary();$t->uuid('model_version_id')->index();$t->string('population',120);$t->integer('sample_size');$t->decimal('brier_score',12,6)->nullable();$t->decimal('log_loss',12,6)->nullable();$t->decimal('roc_auc',12,6)->nullable();$t->decimal('pr_auc',12,6)->nullable();$t->json('bins')->nullable();$t->json('confusion_matrix')->nullable();$t->timestamp('evaluated_at')->index();$t->timestamps();});
  Schema::create('lh_drift_alerts', function(Blueprint $t){$t->uuid('id')->primary();$t->string('drift_type',80)->index();$t->string('feature_key',160)->nullable()->index();$t->string('model_key',120)->nullable()->index();$t->decimal('baseline_value',14,6)->nullable();$t->decimal('current_value',14,6)->nullable();$t->decimal('drift_score',14,6)->nullable();$t->string('severity',30)->index();$t->string('status',30)->default('open')->index();$t->json('evidence')->nullable();$t->timestamp('detected_at')->index();$t->timestamp('resolved_at')->nullable();$t->string('resolved_by')->nullable();$t->timestamps();});
  Schema::create('lh_source_scorecards', function(Blueprint $t){$t->uuid('id')->primary();$t->string('source_key',160)->index();$t->date('period_start');$t->date('period_end');$t->integer('records_ingested')->default(0);$t->integer('unique_entities')->default(0);$t->integer('verified_records')->default(0);$t->integer('qualified_records')->default(0);$t->integer('won_records')->default(0);$t->integer('duplicates')->default(0);$t->integer('risk_flags')->default(0);$t->decimal('evidence_quality',6,2)->nullable();$t->decimal('intent_quality',6,2)->nullable();$t->decimal('conversion_rate',8,4)->nullable();$t->decimal('roi_score',10,4)->nullable();$t->decimal('overall_score',6,2)->nullable();$t->json('metrics')->nullable();$t->timestamps();$t->unique(['source_key','period_start','period_end']);});
  Schema::create('lh_reviewer_scorecards', function(Blueprint $t){$t->uuid('id')->primary();$t->string('reviewer_id',160)->index();$t->date('period_start');$t->date('period_end');$t->integer('cases_reviewed')->default(0);$t->integer('approved')->default(0);$t->integer('rejected')->default(0);$t->integer('reopened')->default(0);$t->integer('overturned')->default(0);$t->decimal('agreement_rate',8,4)->nullable();$t->decimal('median_review_minutes',10,2)->nullable();$t->decimal('quality_score',6,2)->nullable();$t->json('metrics')->nullable();$t->timestamps();$t->unique(['reviewer_id','period_start','period_end']);});
  Schema::create('lh_governance_policies', function(Blueprint $t){$t->uuid('id')->primary();$t->string('policy_key',160)->unique();$t->string('version',40);$t->string('status',30)->default('draft')->index();$t->string('owner')->nullable();$t->json('rules');$t->json('scope')->nullable();$t->timestamp('effective_at')->nullable();$t->timestamp('expires_at')->nullable();$t->timestamps();});
  Schema::create('lh_governance_audits', function(Blueprint $t){$t->uuid('id')->primary();$t->string('event_type',100)->index();$t->string('actor_type',60)->nullable();$t->string('actor_id')->nullable()->index();$t->string('subject_type',80)->nullable();$t->uuid('subject_id')->nullable()->index();$t->string('policy_key')->nullable();$t->string('request_id')->nullable()->index();$t->string('correlation_id')->nullable()->index();$t->json('before_state')->nullable();$t->json('after_state')->nullable();$t->json('reason')->nullable();$t->string('ip_hash',64)->nullable();$t->timestamp('occurred_at')->index();$t->timestamps();});
  Schema::create('lh_data_quality_runs', function(Blueprint $t){$t->uuid('id')->primary();$t->string('scope',120)->index();$t->string('run_type',80);$t->string('status',30)->index();$t->integer('rows_checked')->default(0);$t->integer('errors')->default(0);$t->integer('warnings')->default(0);$t->decimal('quality_score',6,2)->nullable();$t->json('checks')->nullable();$t->json('remediation')->nullable();$t->timestamp('started_at');$t->timestamp('completed_at')->nullable();$t->timestamps();});
  Schema::create('lh_experiments', function(Blueprint $t){$t->uuid('id')->primary();$t->string('experiment_key',160)->unique();$t->string('status',30)->default('draft')->index();$t->string('objective',200);$t->string('unit_type',60)->default('opportunity');$t->json('variants');$t->json('guardrails')->nullable();$t->decimal('minimum_sample',12,2)->nullable();$t->timestamp('starts_at')->nullable();$t->timestamp('ends_at')->nullable();$t->json('results')->nullable();$t->timestamps();});
  Schema::create('lh_experiment_assignments', function(Blueprint $t){$t->uuid('id')->primary();$t->uuid('experiment_id')->index();$t->string('subject_type',80);$t->uuid('subject_id')->index();$t->string('variant',100);$t->string('assignment_hash',64)->unique();$t->timestamp('assigned_at')->index();$t->timestamps();});
  Schema::create('lh_feature_flags', function(Blueprint $t){$t->uuid('id')->primary();$t->string('flag_key',160)->unique();$t->boolean('enabled')->default(false);$t->decimal('rollout_percent',5,2)->default(0);$t->json('conditions')->nullable();$t->string('owner')->nullable();$t->timestamps();});
  Schema::create('lh_retention_policies', function(Blueprint $t){$t->uuid('id')->primary();$t->string('data_class',120)->unique();$t->integer('retention_days')->nullable();$t->string('legal_basis')->nullable();$t->boolean('delete_after_expiry')->default(false);$t->boolean('anonymize_after_expiry')->default(false);$t->json('exceptions')->nullable();$t->timestamps();});
 }
 public function down(): void {foreach(['lh_retention_policies','lh_feature_flags','lh_experiment_assignments','lh_experiments','lh_data_quality_runs','lh_governance_audits','lh_governance_policies','lh_reviewer_scorecards','lh_source_scorecards','lh_drift_alerts','lh_calibration_runs','lh_predictions','lh_model_versions','lh_feature_snapshots','lh_learning_events'] as $t) Schema::dropIfExists($t);}
};
